import { useEffect, useState } from 'react'
import { CalendarDays, Check, ChevronDown, ClipboardList, Clock3, Copy, LogOut, Pause, Play, Plus, RotateCcw, Trash2 } from 'lucide-react'
import { channelNames, dayKey, usePackPilotStore, workers } from './store/usePackPilotStore'
import type { ChannelId, DeliveryType, StageRecord, WorkItem, WorkStage } from './types/work'
import './styles.css'

const channels = Object.entries(channelNames).map(([id, label]) => ({ id: id as ChannelId, label }))
const labels: Record<WorkStage, string> = { picking: '撿貨', sorting: '分貨', packing: '包貨', 'waiting-logistics': '等待寄貨／搬運', shipping: '寄貨', 'moving-hallway': '搬到走廊', 'system-use': '庫存系統作業' }
const coreStages: WorkStage[] = ['picking','sorting','packing']
const logisticsStages: WorkStage[] = ['shipping','moving-hallway']
const fmt = (ms: number) => { const min = Math.max(0, Math.floor(ms / 60000)); return min < 60 ? `${min} 分` : `${Math.floor(min/60)} 小時 ${min%60} 分` }
const sessionMs = (s: StageRecord, now: number) => s.stage === 'waiting-logistics' ? 0 : s.sessions.reduce((sum, x) => sum + (Date.parse(x.endedAt ?? new Date(now).toISOString()) - Date.parse(x.startedAt)), 0)
const waitingMs = (s: StageRecord, now: number) => s.stage !== 'waiting-logistics' ? 0 : s.sessions.reduce((sum, x) => sum + (Date.parse(x.endedAt ?? new Date(now).toISOString()) - Date.parse(x.startedAt)), 0)
const useClock = () => { const [n,setN] = useState(Date.now()); useEffect(() => { const id=setInterval(()=>setN(Date.now()),1000); return()=>clearInterval(id)},[]); return n }

function WorkerPicker({ lead, setLead, helpers, setHelpers, single=false }: { lead:string; setLead:(v:string)=>void; helpers:string[]; setHelpers:(v:string[])=>void; single?:boolean }) {
  return <div className="worker-box"><label>主要執行者<select value={lead} onChange={e=>{setLead(e.target.value);setHelpers(helpers.filter(x=>x!==e.target.value))}}>{workers.map(w=><option key={w}>{w}</option>)}</select></label>{!single&&<div><small>協助人員</small><div className="chips">{workers.filter(w=>w!==lead).map(w=><button type="button" key={w} className={helpers.includes(w)?'chip active':'chip'} onClick={()=>setHelpers(helpers.includes(w)?helpers.filter(x=>x!==w):[...helpers,w])}>{w}</button>)}</div></div>}</div>
}

function StageRow({ work, stage, now }: { work:WorkItem; stage:StageRecord; now:number }) {
  const startStage=usePackPilotStore(s=>s.startStage), complete=usePackPilotStore(s=>s.completeStage), pause=usePackPilotStore(s=>s.pauseStage), resume=usePackPilotStore(s=>s.resumeStage)
  const [open,setOpen]=useState(false), [lead,setLead]=useState(stage.leadWorker||'韋'), [helpers,setHelpers]=useState(stage.helpers)
  const isWait=stage.stage==='waiting-logistics'; const duration=isWait?waitingMs(stage,now):sessionMs(stage,now)
  const logisticsStart = isWait && stage.status==='waiting'
  const nextStage = work.deliveryType==='home-delivery'?'moving-hallway':'shipping'
  if (isWait) return <div className="stage-row waiting-row"><div><strong>{labels[stage.stage]}</strong><span>自動狀態 · 不計入效率</span></div><b>{stage.status==='waiting'?fmt(duration):'尚未進入'}</b>{logisticsStart&&<button className="primary small" onClick={()=>{setOpen(true)}}><Play size={16}/>開始{labels[nextStage]}</button>}{open&&<div className="inline-editor"><WorkerPicker lead={lead} setLead={setLead} helpers={helpers} setHelpers={setHelpers}/><button className="primary" onClick={()=>{startStage(work.id,nextStage,lead,helpers);setOpen(false)}}>開始物流計時</button></div>}</div>
  return <div className={`stage-row status-${stage.status}`}><div><strong>{labels[stage.stage]}</strong><span>{stage.leadWorker?`主要：${stage.leadWorker}${stage.helpers.length?` · 協助：${stage.helpers.join('、')}`:''}`:'尚未指定'}</span></div><b>{fmt(duration)}</b><div className="stage-actions">{stage.status==='not-started'&&<button onClick={()=>setOpen(!open)}><Play size={16}/>開始</button>}{stage.status==='working'&&<><button onClick={()=>pause(work.id,stage.stage)}><Pause size={16}/>暫停</button><button className="done" onClick={()=>complete(work.id,stage.stage)}><Check size={16}/>完成</button></>}{stage.status==='paused'&&<button onClick={()=>resume(work.id,stage.stage)}><Play size={16}/>恢復</button>}{stage.status==='completed'&&<span className="done-label">已完成</span>}</div>{open&&<div className="inline-editor"><WorkerPicker lead={lead} setLead={setLead} helpers={helpers} setHelpers={setHelpers} single={stage.stage==='sorting'}/><button className="primary" onClick={()=>{startStage(work.id,stage.stage,lead,helpers);setOpen(false)}}>開始計時</button></div>}</div>
}

function WorkCard({ work, now }: { work:WorkItem; now:number }) {
  const resumeWork=usePackPilotStore(s=>s.resumeWork), suspend=usePackPilotStore(s=>s.suspendWork), cancel=usePackPilotStore(s=>s.cancelWork), del=usePackPilotStore(s=>s.deleteWork)
  const [open,setOpen]=useState(true)
  const core=work.stages.filter(s=>coreStages.includes(s.stage)).reduce((n,s)=>n+sessionMs(s,now),0), logistics=work.stages.filter(s=>logisticsStages.includes(s.stage)).reduce((n,s)=>n+sessionMs(s,now),0), waiting=work.stages.reduce((n,s)=>n+waitingMs(s,now),0)
  return <article className={`work-card ${work.status}`}><header><button className="card-title" onClick={()=>setOpen(!open)}><div><strong>{work.displayName}</strong><span>{work.orderCount} 單 · {work.deliveryType==='home-delivery'?'宅配':work.deliveryType==='internal'?'內部':'超商'} · 建立 {work.originWorkday}</span></div><ChevronDown className={open?'rotated':''}/></button><div className="status-pill">{work.status==='suspended'?'跨日待續':work.status==='waiting'?'等待物流':work.status==='completed'?'已完成':work.status==='cancelled'?'已取消':'進行中'}</div></header><div className="metrics"><span>核心作業 <b>{fmt(core)}</b></span><span>物流 <b>{fmt(logistics)}</b></span><span>等待 <b>{fmt(waiting)}</b></span></div>{work.status==='suspended'&&<div className="handoff"><div><strong>昨日擱置工作</strong><span>從目前進度接續，擱置時間不計入效率。</span></div><button className="primary" onClick={()=>resumeWork(work.id)}><Play size={16}/>接續工作</button></div>}{open&&<div className="stage-list">{work.stages.map(s=><StageRow key={s.stage} work={work} stage={s} now={now}/>)}</div>}<footer><button onClick={()=>suspend(work.id)} disabled={['completed','cancelled','suspended'].includes(work.status)}><Clock3 size={15}/>擱置到下個工作日</button><button onClick={()=>cancel(work.id)}><LogOut size={15}/>取消</button><button className="danger" onClick={()=>window.confirm('永久刪除？')&&del(work.id)}><Trash2 size={15}/>刪除</button></footer></article>
}

export default function App(){
  const works=usePackPilotStore(s=>s.works), workdays=usePackPilotStore(s=>s.workdays), audits=usePackPilotStore(s=>s.audits), add=usePackPilotStore(s=>s.addWork), endDay=usePackPilotStore(s=>s.endWorkday), reset=usePackPilotStore(s=>s.resetAll), now=useClock()
  const [tab,setTab]=useState<'today'|'log'|'report'>('today'), [form,setForm]=useState(false), [channel,setChannel]=useState<ChannelId>('shopee'), [delivery,setDelivery]=useState<DeliveryType>('convenience-store'), [orders,setOrders]=useState('1'), [lead,setLead]=useState('韋'), [helpers,setHelpers]=useState<string[]>([]), [note,setNote]=useState(''), [selectedDay,setSelectedDay]=useState(dayKey())
  const today=dayKey(); const carry=works.filter(w=>w.status==='suspended'); const current=works.filter(w=>w.currentWorkday===today && !['cancelled','suspended'].includes(w.status)); const completeToday=works.filter(w=>w.completedAt?.startsWith(today));
  const dayWorks=works.filter(w=>w.originWorkday===selectedDay||w.currentWorkday===selectedDay||w.completedAt?.startsWith(selectedDay));
  const totalOrders=completeToday.reduce((n,w)=>n+w.orderCount,0); const totalCore=completeToday.reduce((n,w)=>n+w.stages.filter(s=>coreStages.includes(s.stage)).reduce((a,s)=>a+sessionMs(s,now),0),0)
  const report=`【${today} 工作回報】\n完成批次：${completeToday.length}\n完成單數：${totalOrders}\n核心作業時間：${fmt(totalCore)}\n\n未完成待續：${works.filter(w=>w.status==='suspended').length}\n等待物流：${works.filter(w=>w.status==='waiting').length}`
  const submit=()=>{add({channelId:channel,deliveryType:delivery,orderCount:Number(orders)||0,leadWorker:lead,helpers,note});setForm(false);setNote('')}
  return <main className="app-shell"><header className="hero"><div><p className="eyebrow">PACKPILOT · V0.5 試作版</p><h1>工作跨日不斷線，效率也不替下班時間背黑鍋。</h1><p>{today} · 固定工作者、多人協作、自動等待物流、工作日結算與跨日接續。</p></div><button className="icon" onClick={()=>window.confirm('清除所有試作資料？')&&reset()}><RotateCcw/></button></header>
  <nav className="tabs"><button className={tab==='today'?'active':''} onClick={()=>setTab('today')}><Clock3/>今日工作</button><button className={tab==='log'?'active':''} onClick={()=>setTab('log')}><CalendarDays/>工作日誌</button><button className={tab==='report'?'active':''} onClick={()=>setTab('report')}><ClipboardList/>工作回報</button></nav>
  {tab==='today'&&<><section className="summary-grid"><div><small>今日完成</small><strong>{totalOrders}</strong><span>{completeToday.length} 批</span></div><div><small>核心作業</small><strong>{fmt(totalCore)}</strong><span>不含等待與擱置</span></div><div><small>跨日待續</small><strong>{carry.length}</strong><span>可直接接續</span></div><div><small>等待物流</small><strong>{works.filter(w=>w.status==='waiting').length}</strong><span>不計效率</span></div></section>
  {carry.length>0&&<section><div className="section-title"><h2>昨日待續</h2><span>{carry.length}</span></div><div className="stack">{carry.map(w=><WorkCard key={w.id} work={w} now={now}/>)}</div></section>}
  <div className="main-actions"><button className="new-work" onClick={()=>setForm(!form)}><Plus/>新增工作</button><button className="end-day" onClick={()=>window.confirm('結束今天工作？所有未完成工作會停止計時並轉為跨日待續。')&&endDay()}><LogOut/>結束今天工作</button></div>
  {form&&<section className="create-panel"><label>通路<select value={channel} onChange={e=>setChannel(e.target.value as ChannelId)}>{channels.map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select></label>{channel!=='inventory-system'&&<><label>配送<select value={delivery} onChange={e=>setDelivery(e.target.value as DeliveryType)}><option value="convenience-store">超商</option><option value="home-delivery">宅配</option></select></label><label>單數<input type="number" min="0" value={orders} onChange={e=>setOrders(e.target.value)}/></label></>}<WorkerPicker lead={lead} setLead={setLead} helpers={helpers} setHelpers={setHelpers}/><label className="full">備註<input value={note} onChange={e=>setNote(e.target.value)}/></label><button className="primary full" onClick={submit}>建立並開始第一階段</button></section>}
  <section><div className="section-title"><h2>今天的工作</h2><span>{current.length}</span></div><div className="stack">{current.length?current.map(w=><WorkCard key={w.id} work={w} now={now}/>):<div className="empty">今天尚未建立工作</div>}</div></section></>}
  {tab==='log'&&<section><div className="section-title"><h2>工作日誌</h2><span>{workdays.length}</span></div><div className="day-picker">{[...new Set([today,...workdays.map(d=>d.date),...works.map(w=>w.originWorkday)])].sort().reverse().map(d=><button className={selectedDay===d?'active':''} onClick={()=>setSelectedDay(d)} key={d}>{d}</button>)}</div><div className="stack">{dayWorks.length?dayWorks.map(w=><WorkCard key={w.id} work={w} now={now}/>):<div className="empty">這一天沒有紀錄</div>}</div><div className="audit"><h3>當日事件</h3>{audits.filter(a=>a.happenedAt.startsWith(selectedDay)).map(a=><p key={a.id}><b>{a.action}</b><span>{a.detail}</span><small>{new Date(a.happenedAt).toLocaleTimeString('zh-TW')}</small></p>)}</div></section>}
  {tab==='report'&&<section><div className="section-title"><h2>今日回報試作</h2></div><textarea readOnly value={report}/><button className="primary" onClick={()=>navigator.clipboard.writeText(report)}><Copy size={17}/>複製回報</button><p className="hint">目前先提供精簡版。完整人員、通路與階段明細會在正式版擴充。</p></section>}
  </main>
}
